spring.application.name=ecommerce-service
server.port=8080
replica.which=2

spring.datasource.url=jdbc:postgresql://database:5432/ecommerce-bonus-log-db
spring.datasource.username=ecommerce
spring.datasource.password=papasord

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=2s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.storeService.base-config=default

resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=500ms
resilience4j.retry.instances.storeServiceRetry.base-config=default