services:
  ecommerce:
    build:
      context: ./ecommerce-service/
      dockerfile: devops/Dockerfile
      target: app
    container_name: ecommerce-service
    ports:
      - "8080:8080"
    environment:
      STORE_REPLICA_NAME: "diamond-ecommerce-store"
      EXCHANGE_URL: "http://exchange:8082"
      STORE_URL: "http://store:8081"
      FIDELITY_URL: "http://fidelity:8083"
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ecommerce-bonus-log-db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ecommerce
      SPRING_RABBITMQ_PASSWORD: papasord
    depends_on:
      - store
      - exchange
      - fidelity
      - database
      - rabbitmq

  store:
    build:
      context: ./store-service/
      dockerfile: devops/Dockerfile
      target: app
    ports:
      - "3000-3002:8081"
    environment:
      STORE_SELL_ERROR_PROBABILITY: "0.1"
      STORE_PRODUCT_ERROR_PROBABILITY: "0.2"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  exchange:
    build:
      context: ./exchange-service/
      dockerfile: devops/Dockerfile
      target: app
    ports:
      - "8082"
    environment:
      EXCHANGE_ERROR_PROBABILITY: "0.1"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  fidelity:
    build:
      context: ./fidelity-service/
      dockerfile: devops/Dockerfile
      target: app
    container_name: fidelity-service
    ports:
      - "8083:8083"
    environment:
      FIDELITY_ERROR_PROBABILITY: "0.1"

  database:
    image: postgres:13
    restart: always
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - ./dbfiles:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: papasord
      POSTGRES_USER: ecommerce
      POSTGRES_DB: ecommerce-bonus-log-db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ecommerce
      RABBITMQ_DEFAULT_PASS: papasord
