services:
  ecommerce:
    build:
      context: ./ecommerce-service/
      dockerfile: devops/Dockerfile
      target: app
    container_name: ecommerce-service
    ports:
      - "8080:8080"
    environment:
      STORE_REPLICA_NAME: "diamond-ecommerce-store"
      EXCHANGE_URL: "http://exchange:8082"
      FIDELITY_URL: "http://fidelity:8083"
    depends_on:
      - store
      - exchange
      # - fidelity

  store:
    build:
      context: ./store-service/
      dockerfile: devops/Dockerfile
      target: app
    ports:
      - "3000-3002:8081"
    environment:
      ECOMMERCE_URL: "http://ecommerce:8080"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  exchange:
    build:
      context: ./exchange-service/
      dockerfile: devops/Dockerfile
      target: app
    ports:
      - "8082"
    environment:
      ECOMMERCE_URL: "http://ecommerce:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # fidelity:
  #   build:
  #     context: ./fidelity-service/
  #     dockerfile: devops/Dockerfile
  #     target: app
  #   container_name: fidelity-service
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     ECOMMERCE_URL: "http://ecommerce:8080"
